---
- block:
  - name: Add deadsnakes ppa
    apt_repository:
      repo: "ppa:deadsnakes/ppa"
      update_cache: yes
      state: present

  - name: Install python packages
    apt:
      name:
        - python3.7
        - python3.7-dev
        - python3.7-distutils
        - python3-pip
        - python-virtualenv
        - virtualenvwrapper
        - libxml2-dev
        - libxslt1-dev
        - gettext
        - python-levenshtein
      state: present

  - name: create directory /home/ubuntu/.ssh
    file:
      path: "/home/ubuntu/.ssh"
      state: directory
    become_user: "{{ system.user }}"
    become: yes

  - name: Copy ssh config to remote system
    template:
      src: "{{ playbook_dir }}/roles/django/files/ssh/config"
      dest: "{{ system.home_path }}/.ssh/config"
      owner: "{{ system.user }}"
      group: "{{ system.user }}"
      mode: 0600

  - name: Copy gitlab_deploy_key to remote system
    copy:
      src: "{{ playbook_dir }}/roles/django/files/ssh/gitlab_deploy_key"
      dest: "{{ system.home_path }}/.ssh/gitlab_com_rsa"
      owner: "{{ system.user }}"
      group: "{{ system.user }}"
      mode: 0600

  - name: Config virtualenv
    include: roles/django/tasks/virtualenv.yml

  - name: Checkout latest project code
    git:
      repo: "{{ project.repo_url }}"
      version: "{{ project.branch }}"
      dest: "{{ project.path }}"
      force: yes
      key_file: "{{ system.home_path }}/.ssh/id_rsa.github"
      accept_hostkey: yes
    become_user: "{{ system.user }}"
    become: yes
    when: ansible_nodename != "dev"

  - name: update pip to latest version
    pip:
      name: pip
      state: latest
      virtualenv: "{{ project.virtualenv_path }}"
    become_user: "{{ system.user }}"
    become: yes

  - name: pip install requirement packages
    pip:
      requirements: "{{ project.path }}/requirements.txt"
      virtualenv: "{{ project.virtualenv_path }}"
    become_user: "{{ system.user }}"
    become: yes
