---
- block:
  - name: Config virtualenv
    include: roles/django/tasks/virtualenv.yml

  - name: update pip to latest version
    pip:
      name: pip
      state: latest
      virtualenv: "{{ project.virtualenv_path }}"
    become_user: "{{ system.user }}"
    become: yes

  - name: pip install requirement packages
    pip:
      requirements: "{{ project.path }}/requirements.txt"
      virtualenv: "{{ project.virtualenv_path }}"
    become_user: "{{ system.user }}"
    become: yes
