---
- name: Check virtualenv exists
  stat: path={{ project.virtualenv_path }}
  register: virtualenv_exists

- name: Create virtualenv
  command: "virtualenv -p /usr/bin/python3.7 {{ project.virtualenv_path }}"
  become_user: "{{ system.user }}"
  become: yes
  when: not virtualenv_exists.stat.exists

- name: Copy postactivate to remote system
  template:
    src: "roles/django/files/{{ project.name }}/postactivate"
    dest: "{{ project.virtualenv_path }}/bin/postactivate"
    owner: "{{ system.user }}"
    group: "{{ system.user }}"
    mode: 0755

- name: Create directory /var/www
  file:
    path: "/var/www/"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Copy django-bash-completion-file
  template:
    src: "roles/django/files/{{ project.name }}/django_bash_completion.sh"
    dest: "{{ system.home_path }}/django_bash_completion.sh"
    owner: "{{ system.user }}"
    group: "{{ system.user }}"
    mode: 0755